<!--
	ReportCard Component
	
	A specialized card component for displaying report information.
	Used specifically for the reports page with different layouts and actions based on status.
	
	Props:
	- report: Report data object
	- layout: Display layout ('card' | 'table-row')
	- onDownload: Download action handler
	- onView: View action handler
	- onShare: Share action handler
	- onDelete: Delete action handler
	- onRegenerate: Regenerate action handler
	- onCancel: Cancel action handler
	- class: Additional CSS classes
-->

<script lang="ts">
	import DataCard from '../data/DataCard.svelte';
	import ProgressBar from '../ui/ProgressBar.svelte';
	
	interface ReportData {
		id: number;
		name: string;
		type: string;
		status: string;
		generatedDate: string;
		fileSize: string;
		format: string;
		downloadCount: number;
		generatedBy: string;
	}
	
	interface Props {
		report: ReportData;
		layout?: 'card' | 'table-row';
		onDownload?: () => void;
		onView?: () => void;
		onShare?: () => void;
		onDelete?: () => void;
		onRegenerate?: () => void;
		onCancel?: () => void;
		class?: string;
	}
	
	let {
		report,
		layout = 'card',
		onDownload,
		onView,
		onShare,
		onDelete,
		onRegenerate,
		onCancel,
		class: className = ''
	}: Props = $props();
	
	// Map report status to status variant
	function getStatusVariant(status: string) {
		if (!status) return 'default';
		
		switch (status) {
			case 'Generated': return 'success';
			case 'Processing': return 'info';
			case 'Failed': return 'error';
			case 'Scheduled': return 'warning';
			default: return 'default';
		}
	}
	
	// Get actions based on status
	function getActions(status: string): string[] {
		if (!status) return ['delete'];
		
		switch (status) {
			case 'Generated':
				return ['download', 'view', 'share', 'delete'];
			case 'Processing':
				return ['delete'];
			case 'Failed':
				return ['delete'];
			case 'Scheduled':
				return ['delete'];
			default:
				return ['delete'];
		}
	}
	
	// Build metadata object
	const metadata = {
		'Generated': report.generatedDate ? new Date(report.generatedDate).toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric'
		}) : 'N/A',
		'Size': report.fileSize === '0 MB' ? 'N/A' : report.fileSize || 'N/A',
		'Downloads': (report.downloadCount || 0).toString(),
		'Generated By': report.generatedBy || 'Unknown'
	};
	
	// Custom action handlers based on status
	const actionHandlers = {
		onDownload: report.status === 'Generated' ? onDownload : undefined,
		onView: report.status === 'Generated' ? onView : undefined,
		onShare: report.status === 'Generated' ? onShare : undefined,
		onDelete,
		onExport: onRegenerate // Map regenerate to export action for failed reports
	};
</script>

{#if layout === 'card'}
	<div class={className}>
		<DataCard
			title={report.name}
			subtitle="{report.type} • {report.format}"
			status={report.status}
			statusVariant={getStatusVariant(report.status)}
			progress={report.status === 'Processing' ? 75 : undefined}
			metadata={metadata}
			actions={getActions(report.status)}
			onDownload={actionHandlers.onDownload}
			onView={actionHandlers.onView}
			onShare={actionHandlers.onShare}
			onDelete={actionHandlers.onDelete}
			onExport={actionHandlers.onExport}
		/>
		
		<!-- Custom processing indicator -->
		{#if report.status === 'Processing'}
			<div class="mt-2 px-4">
				<ProgressBar value={75} showLabel color="var(--color-primary)" />
			</div>
		{/if}
	</div>
{:else}
	<!-- Table row layout would be implemented here for table view -->
	<div class="table-row-layout {className}">
		<!-- This would be a table row implementation -->
		<!-- For now, fall back to card layout -->
		<DataCard
			title={report.name}
			subtitle="{report.type} • {report.format}"
			status={report.status}
			statusVariant={getStatusVariant(report.status)}
			metadata={metadata}
			actions={getActions(report.status)}
			onDownload={actionHandlers.onDownload}
			onView={actionHandlers.onView}
			onShare={actionHandlers.onShare}
			onDelete={actionHandlers.onDelete}
			onExport={actionHandlers.onExport}
		/>
	</div>
{/if}
